services:
  postgres:
    image: postgres:16-alpine
    container_name: x_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: nb
      POSTGRES_PASSWORD: nb
      POSTGRES_DB: x_db