services:
  postgres:
    image: postgres:16-alpine
    container_name: x_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: nb
      POSTGRES_PASSWORD: nb
      POSTGRES_DB: x_db

  app:
    build: .
    container_name: x_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/x_db
      SPRING_DATASOURCE_USERNAME: nb
      SPRING_DATASOURCE_PASSWORD: nb
    ports:
      - "8080:8080"